import { test, expect, type Page } from "@playwright/test";
import { createHmac } from "node:crypto";
const primary=process.env.SFU_PRIMARY_URL??"http://127.0.0.1:4100", secret=process.env.ROOM_ACCESS_SECRET??"integration-secret";
const token=(r:string,u:string)=>{const p=Buffer.from(JSON.stringify({roomId:r,userId:u,role:"participant",exp:Math.floor(Date.now()/1000)+600})).toString("base64url");return p+"."+createHmac("sha256",secret).update(p).digest("base64url")};
async function join(page:Page,r:string,u:string,peer=""){return page.evaluate(async({r,u,accessToken,peer})=>{
 const s:any=globalThis.__rejoin??={stream:undefined,ws:undefined,pc:undefined};s.ws?.close();s.pc?.close();s.stream??=await navigator.mediaDevices.getUserMedia({video:true,audio:false});const pc=new RTCPeerConnection();s.stream.getTracks().forEach((t:MediaStreamTrack)=>pc.addTrack(t,s.stream));
 const ws=new WebSocket(location.origin.replace(/^http/,"ws")+"/ws");const q:any[]=[];const w=new Map<string,((x:any)=>void)[]>();const wait=(t:string)=>new Promise<any>((res,rej)=>{const tm=setTimeout(()=>rej(Error(t)),12000);const i=q.findIndex(x=>x.type===t);if(i>=0){clearTimeout(tm);return res(q.splice(i,1)[0])}const a=w.get(t)??[];a.push(x=>{clearTimeout(tm);res(x)});w.set(t,a)});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="ice"&&m.data)void pc.addIceCandidate(m.data);const a=w.get(m.type);if(a?.length)a.shift()!(m);else q.push(m)};await new Promise<void>((res,rej)=>{ws.onopen=()=>res();ws.onerror=()=>rej(Error("ws"))});pc.onicecandidate=e=>{if(e.candidate&&ws.readyState===1)ws.send(JSON.stringify({type:"ice",r,data:e.candidate.toJSON()}))};ws.send(JSON.stringify({type:"join",r,data:{accessToken,reconnect:!!peer,...peer?{peerId:peer}:{}}}));const j=await wait("joined");const o=await pc.createOffer();await pc.setLocalDescription(o);ws.send(JSON.stringify({type:"offer",r,data:pc.localDescription}));const a=await wait("answer");if(a.data)await pc.setRemoteDescription(a.data);s.ws=ws;s.pc=pc;return j.peerId;
 },{r,u,accessToken:token(r,u),peer})}
test("peer reconnect preserves identity through rapid close and reopen",async({browser})=>{
 test.skip(!process.env.SFU_FAILOVER_LIVE,"Set SFU_FAILOVER_LIVE=1");const p=await browser.newPage();const room="REJOIN-"+Date.now();try{
  const peer=await join(p,room,"rejoin-user");const seen=new Set([peer]);for(let i=0;i<12;i++){const next=await join(p,room,"rejoin-user",peer);expect(next).toBe(peer);seen.add(next)}expect(seen.size).toBe(1)
 }finally{await p.close()}
});